name: CI
on: 
  push:
    paths-ignore:
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
      - "docs/**"
      - '**.md'
      - '**.txt'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - "docs/**"
      - '**.md'
      - '**.txt'
      - 'LICENSE'
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            build_script: ./script/build.sh
            build_suffix: tar.gz
          - platform: macos-latest
            build_script: ./script/build.sh
            build_suffix: tar.gz
          - platform: windows-latest
            build_script: script/build.bat
            build_suffix: zip
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Build Bloat
        run: ${{ matrix.build_script }}
      - name: Upload release
        uses: svenstaro/upload-release-action@v1-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_glob: true
          file: bloat-*.${{ matrix.build_suffix }}
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
